-- =====================================================
-- D&D 3.5 SRD CLASSES - SAMPLE INSERT STATEMENTS
-- =====================================================
-- Schema: pnpo_3_5_dev.classes
-- Source: SRD HTML exports (character-classes-i.html, character-classes-ii.html)

SET search_path TO pnpo_3_5_dev;

-- =====================================================
-- EXAMPLE CLASS INSERT: BARBARIAN
-- =====================================================

-- Example: BARBARIAN (Base class, non-spellcaster, d12 HD)
INSERT INTO classes (
  name,
  hit_die,
  class_type,
  race_id,
  base_attack_bonus_progression,
  fortitude_progression,
  reflex_progression,
  will_progression,
  skill_points_per_level,
  is_spellcaster,
  spellcasting_ability,
  spell_progression_type,
  description
) VALUES (
  'Barbarian',
  12,
  'base',
  NULL,
  'full',
  'good',
  'poor',
  'poor',
  4,
  false,
  NULL,
  NULL,
  'A ferocious warrior who can enter a battle rage to gain tremendous strength and durability. Barbarians excel as frontline combatants and have unmatched endurance and mobility. They are illiterate by default but can learn to read and write by spending skill points.'
);

-- =====================================================
-- BARBARIAN CLASS SKILLS
-- =====================================================
-- NOTE: Class skills are linked via class_skills junction table (not shown here).
-- See D:\Workspace\WEB\PROJECTS\pnpo\database\schemas\pnpo_3_5_dev\tables\classes.sql
--
-- Barbarian class skills:
-- - Climb (Str)
-- - Craft (Int)
-- - Handle Animal (Cha)
-- - Intimidate (Cha)
-- - Jump (Str)
-- - Listen (Wis)
-- - Ride (Dex)
-- - Survival (Wis)
-- - Swim (Str)
--
-- These would be linked via:
-- INSERT INTO class_skills (class_id, skill_id)
-- VALUES
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), (SELECT id FROM skills WHERE name = 'Climb')),
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), (SELECT id FROM skills WHERE name = 'Craft')),
--   -- ... etc for all class skills
-- ;

-- =====================================================
-- BARBARIAN CLASS ABILITIES
-- =====================================================
-- NOTE: Class abilities are now managed through the unified special_abilities system.
-- See special_abilities.sql for the class_granted_abilities junction table.
--
-- Barbarian abilities are defined in special_abilities table and linked to the class
-- via class_granted_abilities with granted_at_level tracking.
--
-- This follows the same pattern as:
-- - race_granted_abilities (race → special_abilities)
-- - feat_granted_abilities (feat → special_abilities)
-- - domain_granted_abilities (domain → special_abilities)
--
-- =====================================================
-- BARBARIAN PROGRESSION (Levels 1-20)
-- =====================================================
--
-- Level  Special Abilities
-- -----  -----------------
-- 1st    Fast movement, illiteracy, rage 1/day
-- 2nd    Uncanny dodge
-- 3rd    Trap sense +1
-- 4th    Rage 2/day
-- 5th    Improved uncanny dodge
-- 6th    Trap sense +2
-- 7th    Damage reduction 1/—
-- 8th    Rage 3/day
-- 9th    Trap sense +3
-- 10th   Damage reduction 2/—
-- 11th   Greater rage
-- 12th   Rage 4/day, trap sense +4
-- 13th   Damage reduction 3/—
-- 14th   Indomitable will
-- 15th   Trap sense +5
-- 16th   Damage reduction 4/—, rage 5/day
-- 17th   Tireless rage
-- 18th   Trap sense +6
-- 19th   Damage reduction 5/—
-- 20th   Mighty rage, rage 6/day
--
-- =====================================================
-- BARBARIAN ABILITIES (via special_abilities system)
-- =====================================================
--
-- Step 1: Create special_abilities for barbarian abilities
-- Step 2: Link abilities to barbarian class via class_granted_abilities
-- Step 3: Create effects/formulas for scaling abilities (Rage, Trap Sense, DR)
--
-- Example: Fast Movement ability
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Fast Movement',
--   'extraordinary',
--   false,
--   'passive',
--   'A barbarian''s land speed is faster than the norm for his race by +10 feet. This benefit applies only when he is wearing no armor, light armor, or medium armor and not carrying a heavy load. Apply this bonus before modifying the barbarian''s speed because of any load carried or armor worn.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1001
--
-- Example: Link Fast Movement to Barbarian level 1
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1001,  -- Fast Movement ability ID
--   1,
--   1,
--   false
-- );
--
-- Example: Rage ability (scales with uses per day)
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Rage',
--   'extraordinary',
--   true,
--   'free',
--   'A barbarian can fly into a rage a certain number of times per day. In a rage, a barbarian temporarily gains a +4 bonus to Strength, a +4 bonus to Constitution, and a +2 morale bonus on Will saves, but he takes a –2 penalty to Armor Class. The increase in Constitution increases the barbarian''s hit points by 2 points per level, but these hit points go away at the end of the rage when his Constitution score drops back to normal. A barbarian may call upon his rage ability only once per encounter. At 1st level he can use his rage ability once per day. At 4th level and every four levels thereafter, he can use it one additional time per day. Entering a rage takes no time itself, but a barbarian can do it only during his action, not in response to someone else''s action. A barbarian can''t, for example, use his rage ability when struck down by an arrow in order to get the extra hit points from the increased Constitution. A rage lasts for a number of rounds equal to 3 + the character''s (newly improved) Constitution modifier. A barbarian may prematurely end his rage. At the end of the rage, the barbarian loses the rage modifiers and restrictions and becomes fatigued (–2 penalty to Strength, –2 penalty to Dexterity, can''t charge or run) for the duration of the current encounter.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1002
--
-- Rage progression (improves uses per day):
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1002, 1, 1, false),   -- 1/day
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1002, 4, 1, true),    -- 2/day
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1002, 8, 1, true),    -- 3/day
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1002, 12, 1, true),   -- 4/day
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1002, 16, 1, true),   -- 5/day
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1002, 20, 1, true);   -- 6/day
--
-- Example: Uncanny Dodge ability
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Uncanny Dodge',
--   'extraordinary',
--   false,
--   'passive',
--   'At 2nd level, a barbarian retains his Dexterity bonus to AC (if any) even if he is caught flat-footed or struck by an invisible attacker. However, he still loses his Dexterity bonus to AC if immobilized. If a barbarian already has uncanny dodge from a different class he automatically gains improved uncanny dodge instead.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1003
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1003,
--   2,
--   2,
--   false
-- );
--
-- Example: Trap Sense ability (scales with bonus amount)
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Trap Sense',
--   'extraordinary',
--   false,
--   'passive',
--   'Starting at 3rd level, a barbarian gains a +1 bonus on Reflex saves made to avoid traps and a +1 dodge bonus to AC against attacks made by traps. These bonuses rise by +1 every three barbarian levels thereafter (6th, 9th, 12th, 15th, and 18th level). Trap sense bonuses gained from multiple classes stack.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1004
--
-- Trap Sense progression (with scaling formula):
-- First, create formula for scaling bonus:
-- INSERT INTO formulas (name, formula_type, formula_expression, description)
-- VALUES (
--   'Trap Sense Bonus',
--   'scaling',
--   'FLOOR((barbarian_level - 3) / 3) + 1',
--   'Trap sense bonus: +1 at 3rd, +2 at 6th, +3 at 9th, etc.'
-- ) RETURNING id;  -- Assume returns 2001
--
-- Link with formula:
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, progression_formula_id, first_gained_at_level, improves_existing)
-- VALUES
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1004, 3, 2001, 3, false),    -- +1
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1004, 6, 2001, 3, true),     -- +2
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1004, 9, 2001, 3, true),     -- +3
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1004, 12, 2001, 3, true),    -- +4
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1004, 15, 2001, 3, true),    -- +5
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1004, 18, 2001, 3, true);    -- +6
--
-- Example: Improved Uncanny Dodge ability
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Improved Uncanny Dodge',
--   'extraordinary',
--   false,
--   'passive',
--   'At 5th level and higher, a barbarian can no longer be flanked. This defense denies a rogue the ability to sneak attack the barbarian by flanking him, unless the attacker has at least four more rogue levels than the target has barbarian levels. If a character already has uncanny dodge from a second class, the character automatically gains improved uncanny dodge instead, and the levels from the classes that grant uncanny dodge stack to determine the minimum level a rogue must be to flank the character.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1005
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1005,
--   5,
--   5,
--   false
-- );
--
-- Example: Damage Reduction ability (scales with amount)
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Damage Reduction',
--   'extraordinary',
--   false,
--   'passive',
--   'At 7th level, a barbarian gains Damage Reduction. Subtract 1 from the damage the barbarian takes each time he is dealt damage from a weapon or a natural attack. At 10th level, and every three barbarian levels thereafter (13th, 16th, and 19th level), this damage reduction rises by 1 point. Damage reduction can reduce damage to 0 but not below 0.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1006
--
-- Damage Reduction progression:
-- INSERT INTO formulas (name, formula_type, formula_expression, description)
-- VALUES (
--   'Barbarian DR',
--   'scaling',
--   'FLOOR((barbarian_level - 7) / 3) + 1',
--   'DR amount: 1/— at 7th, 2/— at 10th, 3/— at 13th, etc.'
-- ) RETURNING id;  -- Assume returns 2002
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, progression_formula_id, first_gained_at_level, improves_existing)
-- VALUES
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1006, 7, 2002, 7, false),    -- DR 1/—
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1006, 10, 2002, 7, true),    -- DR 2/—
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1006, 13, 2002, 7, true),    -- DR 3/—
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1006, 16, 2002, 7, true),    -- DR 4/—
--   ((SELECT id FROM classes WHERE name = 'Barbarian'), 1006, 19, 2002, 7, true);    -- DR 5/—
--
-- Example: Greater Rage ability
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Greater Rage',
--   'extraordinary',
--   true,
--   'free',
--   'At 11th level, a barbarian''s bonuses to Strength and Constitution during his rage each increase to +6, and his morale bonus on Will saves increases to +3. The penalty to AC remains at –2.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1007
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1007,
--   11,
--   11,
--   false
-- );
--
-- Example: Indomitable Will ability
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Indomitable Will',
--   'extraordinary',
--   false,
--   'passive',
--   'While in a rage, a barbarian of 14th level or higher gains a +4 bonus on Will saves to resist enchantment spells. This bonus stacks with all other modifiers, including the morale bonus on Will saves he also receives during his rage.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1008
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1008,
--   14,
--   14,
--   false
-- );
--
-- Example: Tireless Rage ability
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Tireless Rage',
--   'extraordinary',
--   false,
--   'passive',
--   'At 17th level and higher, a barbarian no longer becomes fatigued at the end of his rage.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1009
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1009,
--   17,
--   17,
--   false
-- );
--
-- Example: Mighty Rage ability
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Mighty Rage',
--   'extraordinary',
--   true,
--   'free',
--   'At 20th level, a barbarian''s bonuses to Strength and Constitution during his rage each increase to +8, and his morale bonus on Will saves increases to +4. The penalty to AC remains at –2.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1010
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1010,
--   20,
--   20,
--   false
-- );
--
-- Example: Illiteracy special feature
-- INSERT INTO special_abilities (name, ability_type, is_active, activation_type, description, source_category)
-- VALUES (
--   'Illiteracy',
--   'extraordinary',
--   false,
--   'passive',
--   'Barbarians are the only characters who do not automatically know how to read and write. A barbarian may spend 2 skill points to gain the ability to read and write all languages he is able to speak. A barbarian who gains a level in any other class automatically gains literacy. Any other character who gains a barbarian level does not lose the literacy he or she already had.',
--   'class'
-- ) RETURNING id;  -- Assume returns 1011
--
-- INSERT INTO class_granted_abilities (class_id, special_ability_id, granted_at_level, first_gained_at_level, improves_existing)
-- VALUES (
--   (SELECT id FROM classes WHERE name = 'Barbarian'),
--   1011,
--   1,
--   1,
--   false
-- );

-- =====================================================
-- BARBARIAN ABILITY EFFECTS
-- =====================================================
-- Barbarian abilities link to effects system for mechanical bonuses.
-- See effects.sql and special_abilities.sql for the ability_granted_effects junction table.
--
-- Example: Rage grants temporary stat bonuses
-- Step 1: Create effects for Rage
-- INSERT INTO effects (name, effect_type, description)
-- VALUES
--   ('Rage: +4 STR', 'stat', 'Temporary +4 bonus to Strength while raging'),
--   ('Rage: +4 CON', 'stat', 'Temporary +4 bonus to Constitution while raging'),
--   ('Rage: +2 Will', 'save', 'Morale bonus on Will saves while raging'),
--   ('Rage: -2 AC', 'ac', 'Penalty to Armor Class while raging')
-- RETURNING id;  -- Assume returns 3001, 3002, 3003, 3004
--
-- Step 2: Create stat_effects for each
-- INSERT INTO stat_effects (effect_id, stat_name, value, is_temporary)
-- VALUES
--   (3001, 'STR', 4, true),
--   (3002, 'CON', 4, true);
--
-- INSERT INTO save_effects (effect_id, save_type, bonus_type, value)
-- VALUES
--   (3003, 'will', 'morale', 2);
--
-- INSERT INTO ac_effects (effect_id, ac_bonus_type, value)
-- VALUES
--   (3004, 'untyped', -2);
--
-- Step 3: Link effects to Rage ability
-- INSERT INTO ability_granted_effects (special_ability_id, effect_id, active_only)
-- VALUES
--   (1002, 3001, true),  -- Rage ability ID, +4 STR effect, only while rage is active
--   (1002, 3002, true),  -- +4 CON
--   (1002, 3003, true),  -- +2 Will
--   (1002, 3004, true);  -- -2 AC

-- =====================================================
-- NOTES ON SCHEMA MAPPING
-- =====================================================
--
-- Fields mapped from SRD HTML:
-- - name: Class name from h2/h3 heading
-- - hit_die: From "Hit Die:" section (d12 for Barbarian)
-- - class_type: Always 'base' for core classes
-- - base_attack_bonus_progression: Extracted from progression table
--     → full = +1 per level (Fighter, Barbarian, Paladin, Ranger)
--     → medium = +3/4 per level (Cleric, Druid, Monk, Rogue, Bard)
--     → poor = +1/2 per level (Wizard, Sorcerer)
-- - fortitude_progression: From progression table
--     → good = 2 + level/2 (starts +2, +3, +3, +4, +4...)
--     → poor = level/3 (starts +0, +0, +1, +1, +1, +2...)
-- - reflex_progression: Same as fortitude
-- - will_progression: Same as fortitude
-- - skill_points_per_level: From "Skill Points at 1st Level:" section
--     → Extract number (e.g., "(4 + Int modifier) × 4" → 4)
-- - is_spellcaster: Check for "Spells per Day" table
-- - spellcasting_ability: From casting section (INT/WIS/CHA)
-- - spell_progression_type:
--     → full = 9th level spells at 17th level (Wizard, Cleric, Druid)
--     → half = 4th level spells at 13th level (Paladin, Ranger)
--     → partial = 6th level spells at 16th level (Bard)
--     → none = non-spellcaster
--
-- Class abilities mapping:
-- - Extract from "Class Features" section
-- - Parse progression table "Special" column
-- - Create special_abilities entries for each unique ability
-- - Link via class_granted_abilities with granted_at_level
-- - Use progression_formula_id for scaling abilities
-- - Set improves_existing=true for abilities that scale
-- - Set first_gained_at_level to track original level
--
-- Scaling abilities patterns:
-- - Uses per day (Rage: 1/day → 6/day) → improves_existing=true, track uses
-- - Numeric bonuses (Trap Sense: +1 → +6) → progression_formula_id
-- - Damage reduction (DR 1/— → 5/—) → progression_formula_id
-- - Replacement abilities (Rage → Greater Rage → Mighty Rage) → separate abilities
--
-- Edge cases:
-- - Illiteracy is unique to Barbarian (special feature)
-- - Uncanny Dodge stacks with other classes (needs special logic)
-- - Ex-Barbarians: Alignment restriction (Lawful alignment prevents rage)
-- - Fast Movement only applies with light/medium armor or no armor
--
-- Import strategy:
-- 1. Import base class (name, HD, progressions, skills)
-- 2. Create special_abilities for all class features
-- 3. Create formulas for scaling abilities
-- 4. Link via class_granted_abilities with levels
-- 5. Create effects for abilities with mechanical bonuses
-- 6. Link effects via ability_granted_effects
--
-- =====================================================
